#!/bin/bash
#
# StreamLinux Android APK Build Script
# Version: 0.2.0-alpha
# Requires: Java 21, Android SDK, Android Build Tools
#
# Usage:
#   ./build-apk.sh          # Build debug APK
#   ./build-apk.sh release  # Build release APK (requires signing config)
#   ./build-apk.sh clean    # Clean build artifacts
#

set -e

VERSION="0.2.0-alpha"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      StreamLinux Android APK Builder v${VERSION}         ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

BUILD_TYPE="${1:-debug}"

# Check Java 21
echo -e "${YELLOW}[1/5] Checking prerequisites...${NC}"

check_java() {
    if command -v java &> /dev/null; then
        JAVA_VER=$(java -version 2>&1 | head -1 | awk -F '"' '{print $2}' | cut -d'.' -f1)
        echo "  Java version: $JAVA_VER"
        if [ "$JAVA_VER" -lt 21 ]; then
            echo -e "${RED}Error: Java 21 or higher required. Found Java $JAVA_VER${NC}"
            echo ""
            echo "Install Java 21 on Fedora:"
            echo "  sudo dnf install java-21-openjdk-devel"
            echo ""
            echo "Or set JAVA_HOME to Java 21 installation:"
            echo "  export JAVA_HOME=/usr/lib/jvm/java-21-openjdk"
            exit 1
        fi
        echo -e "${GREEN}  ✓ Java $JAVA_VER detected${NC}"
    else
        echo -e "${RED}Error: Java not found${NC}"
        exit 1
    fi
}

check_android_sdk() {
    if [ -z "$ANDROID_HOME" ] && [ -z "$ANDROID_SDK_ROOT" ]; then
        # Try common locations
        POSSIBLE_SDK_PATHS=(
            "$HOME/Android/Sdk"
            "$HOME/android-sdk"
            "/opt/android-sdk"
            "$HOME/Library/Android/sdk"
        )
        
        for sdk_path in "${POSSIBLE_SDK_PATHS[@]}"; do
            if [ -d "$sdk_path" ]; then
                export ANDROID_HOME="$sdk_path"
                export ANDROID_SDK_ROOT="$sdk_path"
                break
            fi
        done
    fi
    
    if [ -z "$ANDROID_HOME" ]; then
        echo -e "${RED}Error: Android SDK not found${NC}"
        echo ""
        echo "Set ANDROID_HOME or ANDROID_SDK_ROOT environment variable:"
        echo "  export ANDROID_HOME=\$HOME/Android/Sdk"
        echo ""
        echo "Or install Android SDK:"
        echo "  https://developer.android.com/studio#command-tools"
        exit 1
    fi
    
    echo "  Android SDK: $ANDROID_HOME"
    echo -e "${GREEN}  ✓ Android SDK detected${NC}"
}

check_java
check_android_sdk

# Check Gradle wrapper
if [ ! -f "$PROJECT_ROOT/gradlew" ]; then
    echo -e "${RED}Error: Gradle wrapper not found${NC}"
    exit 1
fi

chmod +x "$PROJECT_ROOT/gradlew"

# Clean if requested
if [ "$BUILD_TYPE" == "clean" ]; then
    echo -e "${YELLOW}Cleaning build artifacts...${NC}"
    ./gradlew clean
    echo -e "${GREEN}✓ Clean complete${NC}"
    exit 0
fi

# Update local.properties
echo -e "${YELLOW}[2/5] Configuring build environment...${NC}"
cat > "$PROJECT_ROOT/local.properties" << EOF
# Auto-generated by build-apk.sh
sdk.dir=$ANDROID_HOME
EOF
echo -e "${GREEN}  ✓ local.properties configured${NC}"

# Download dependencies
echo -e "${YELLOW}[3/5] Downloading dependencies...${NC}"
./gradlew dependencies --quiet 2>/dev/null || true
echo -e "${GREEN}  ✓ Dependencies ready${NC}"

# Build APK
echo -e "${YELLOW}[4/5] Building APK ($BUILD_TYPE)...${NC}"

if [ "$BUILD_TYPE" == "release" ]; then
    echo -e "${YELLOW}  Building release APK...${NC}"
    
    # Check for signing config
    if [ -z "$KEYSTORE_PATH" ]; then
        echo -e "${YELLOW}  Warning: No signing config found. Building unsigned APK.${NC}"
        echo "  To sign, set environment variables:"
        echo "    export KEYSTORE_PATH=/path/to/keystore.jks"
        echo "    export KEYSTORE_PASSWORD=your_password"
        echo "    export KEY_ALIAS=your_key"
        echo "    export KEY_PASSWORD=your_key_password"
        echo ""
    fi
    
    ./gradlew assembleRelease --no-daemon
    APK_PATH="$PROJECT_ROOT/app/build/outputs/apk/release/app-release-unsigned.apk"
    
    # If signed APK exists, use that instead
    if [ -f "$PROJECT_ROOT/app/build/outputs/apk/release/app-release.apk" ]; then
        APK_PATH="$PROJECT_ROOT/app/build/outputs/apk/release/app-release.apk"
    fi
else
    echo -e "${YELLOW}  Building debug APK...${NC}"
    ./gradlew assembleDebug --no-daemon
    APK_PATH="$PROJECT_ROOT/app/build/outputs/apk/debug/app-debug.apk"
fi

if [ ! -f "$APK_PATH" ]; then
    echo -e "${RED}Error: APK not found at $APK_PATH${NC}"
    echo "Check build logs above for errors."
    exit 1
fi

# Copy to output directory
echo -e "${YELLOW}[5/5] Finalizing...${NC}"
OUTPUT_DIR="$PROJECT_ROOT/../releases/apk"
mkdir -p "$OUTPUT_DIR"

APK_NAME="streamlinux-${VERSION}-${BUILD_TYPE}.apk"
cp "$APK_PATH" "$OUTPUT_DIR/$APK_NAME"

# Get APK info
APK_SIZE=$(du -h "$OUTPUT_DIR/$APK_NAME" | cut -f1)

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    BUILD SUCCESSFUL!                     ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BLUE}APK File:${NC}    $OUTPUT_DIR/$APK_NAME"
echo -e "  ${BLUE}Size:${NC}        $APK_SIZE"
echo -e "  ${BLUE}Build Type:${NC}  $BUILD_TYPE"
echo -e "  ${BLUE}Version:${NC}     $VERSION"
echo ""
echo -e "  ${YELLOW}To install on device (USB debugging enabled):${NC}"
echo "    adb install $OUTPUT_DIR/$APK_NAME"
echo ""
echo -e "  ${YELLOW}To install on emulator:${NC}"
echo "    adb -e install $OUTPUT_DIR/$APK_NAME"
echo ""

if [ "$BUILD_TYPE" == "debug" ]; then
    echo -e "  ${CYAN}Note: This is a debug build. For production, run:${NC}"
    echo "    ./build-apk.sh release"
    echo ""
fi

echo -e "${GREEN}Done!${NC}"
